name: DS-ALGO-C-
on: repository_dispatch
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: ./scripts/fetch-resources.sh

            - name: Update resources
              uses: DSCBITDurg/DS-ALGO-C-@v1
              with:
                  file-path: https://github.com/DSCBITDurg/DS-ALGO-C-#readme
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKENS }}
